kind: Pod
apiVersion: v1
metadata:
  name: mypod
  labels:
    app: ceph_web
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: pvc1
